version: '3.7'

services:
  shorturl:
    image: mawenzhong/go_shorturl:latest
    environment:
      - spring.profiles.active
    ports:
      - 8888:8888
    depends_on:
      - transform
    networks:
      - external_access

  transform:
    image: mawenzhong/go_transform:latest
    environment:
      - spring.profiles.active
    networks:
      - external_access

networks:
  external_access: